# Molecular Emission Lines Search Tool
locale: "en-US"
title: "Chengzheng Yong"
title_separator: "-"
name: &name "Chengzheng (Copland) Yong"
description: &description "Interactive search tool for molecular emission lines with periodic table element filtering"
url: "https://copland-yz.github.io"
baseurl: "/MELT"
repository: "Copland-yz/MELT"

# Site Author
author:
  # Biographic information
  name             : "Chengzheng (Copland) Yong"
  github           : "Copland-yz"


# Site Settings
breadcrumbs: false # true, false (default)
words_per_minute: 160
comments:
  provider: false

atom_feed:
  hide: false     # change to true to hide the RSS feed in the footer
  path: # blank (default) uses feed.xml

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README.md
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-sitemap

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true